import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./app.css";
import Header from "@/components/Header";

import SolanaWalletProvider from "@/providers/SolanaWalletProvider";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Catalyst",
	description: "Generated by create next app",
	icons: {
		icon: "/logo.svg",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiase`}>
				<SolanaWalletProvider>
					<Toaster />
					<div className='w-[80%] mx-auto text-white'>
						<div className='grid--pattern ' />
						<Header />
						{children}
					</div>
				</SolanaWalletProvider>
			</body>
		</html>
	);
}
